### ISSUE TITLE
OPML import into Pocket Casts fails

### ISSUE THREAD

**Issue by mpoetter** [jiacai2050/podcasts-opml-exporter#2]
Pocket Casts 7.11 (782)
iPhone 7, iOS 13.6

<img width="375" alt="Bildschirmfoto 2020-08-22 um 13 38 01" src="https://user-images.githubusercontent.com/6137054/90955297-c1663500-e47c-11ea-800c-d783a6a46ace.png">

**Comment by mpoetter** [comment]
The issue was, that some of my podcast included the letter '&' in the title, which left pocket casts table to read the file. simply deleting all the '&' fixed the problem.

Still the tool could address this issue on its own.

**Comment by jiacai2050** [comment]
PRs are welcomed.

**Comment by jgquinn** [comment]
Thanks for sharing your workaround, @mpoetter. I added a couple of simple replacements in PR #3 .

**Comment by bystritskiy** [comment]
Same issue. I will be waiting approve your PR
