### ISSUE TITLE
TypeError: null is not an object (evaluating 'v.firstChild.nodeValue')

### ISSUE THREAD

**Issue by apple-ihack-geek** [jiacai2050/podcasts-opml-exporter#4]
"TypeError: null is not an object (evaluating 'v.firstChild.nodeValue')"
error when uploading to the website

I added a .txt to the file so i could upload it here to GitHub with this issue
[PodcastsDB.plist.txt](https://github.com/jiacai2050/podcasts-opml-exporter/files/6258624/PodcastsDB.plist.txt)

**Comment by trijste** [comment]
Same issue `TypeError: null is not an object (evaluating 'v.firstChild.nodeValue')`

**Comment by jiacai2050** [comment]
I try your plist file after merge #5, it works as expected.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/3848910/208300208-aa05f2b9-7192-48e8-ad8b-b08dada31fe9.png">
